### ISSUE TITLE
can't start new games after a previous game was aborted

### ISSUE THREAD

**Issue by LordRobust** [VoxelGamesLib/VoxelGamesLibv2#50] opened 2017-07-06 01:38 UTC
error:

```
[02:37:43 INFO]: fusedaphelion issued server command: /game start hideandseek
[02:37:43 FINER]: [VoxelGamesLib] start phaseLobbyPhase
[02:37:43 FINER]: [VoxelGamesLib] TextComponent{content=, children=[TextComponent{content=[ADMIN] , children=[TextComponent{content=fusedaphelion, children=[], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}], color=red, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}, TextComponent{content=, children=[], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null} joined the game HideAndSeek
[02:37:43 FINER]: [VoxelGamesLib] stop phase LobbyPhase
[02:37:43 FINER]: [VoxelGamesLib] start phaseVotePhase
[02:37:43 FINER]: [VoxelGamesLib] stop phase VotePhase
[02:37:43 FINER]: [VoxelGamesLib] start phaseHidingPhase
[02:37:44 FINER]: [VoxelGamesLib] stop phase HidingPhase
[02:37:44 FINER]: [VoxelGamesLib] start phaseHideAndSeekPhase
[02:37:44 FINER]: [VoxelGamesLib] stop phase HideAndSeekPhase
[02:37:44 WARNING]: [VoxelGamesLib] Game finished without a winner?!
[02:37:44 FINER]: [VoxelGamesLib] abort  game
[02:37:44 FINER]: [VoxelGamesLib] TextComponent{content=, children=[TextComponent{content=[ADMIN] , children=[TextComponent{content=fusedaphelion, children=[], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}], color=red, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}, TextComponent{content=, children=[], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null}], color=null, obfuscated=null, bold=null, strikethrough=null, underlined=null, italic=null, clickEvent=null, hoverEvent=null, insertion=null} left the game HideAndSeek
[02:37:44 FINER]: [VoxelGamesLib] stop phase HideAndSeekPhase
[02:37:44 WARNING]: [VoxelGamesLib] Task #4 for VoxelGamesLib v2.0-SNAPSHOT generated an exception
java.util.ConcurrentModificationException
	at java.util.ArrayList.forEach(ArrayList.java:1252)
	at me.minidigger.voxelgameslib.tick.TickHandler.tick(TickHandler.java:34)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
	at java.lang.Thread.run(Thread.java:748)
```

it just instantly cycles through all phases and aborts the game.

**Comment by MiniDigger** [comment] 2017-07-06 07:00
Duplicate of #48

**Closed by MiniDigger** 2017-07-06 07:00 UTC
